name: CI
on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install # will run `yarn install` command

      - name: Run linter
        uses: borales/actions-yarn@v5
        with:
          cmd: run lint # will run `yarn run lint` command

      - name: Build production bundle
        uses: borales/actions-yarn@v5
        with:
          cmd: run build # will run `yarn run build` command
